apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui-deployment
  labels:
    app: karsajobs-ui
spec:
  replicas: 1 # set hanya 1 pod yang akan berjalan
  selector:
    matchLabels:
      app: karsajobs-ui
  template:
    metadata:
      labels:
        app: karsajobs-ui
    spec:
      containers:
      - name: karsajobs-ui
        image: ghcr.io/auzty/karsajobs-ui:latest # pull dari github registry
        imagePullPolicy: Always # akan selalu pull walaupun images ada sudah ada 
        ports:
        - containerPort: 8000 # melakukan expose port 8000 untuk pod yang sedang berjalan
          name: 8000tcp02
          protocol: TCP
