apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-deployment
  labels:
    app: karsajobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs
  template:
    metadata:
      labels:
        app: karsajobs
    spec:
      containers:
      - name: karsajobs
        env:
        - name: APP_PORT # set port aplikasi karsajob ke 8080
          value: "8080"
        - name: MONGO_HOST
          value: mongodb-service.default.svc.cluster.local # set mongodb host menggunakan internal cluster
        - name: MONGO_USER
          valueFrom:
            secretKeyRef: # mengambil username dari kubernetes secret
              name: mongo-secret
              key: MONGO_ROOT_USERNAME
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef: # mengambil password dari kubernetes secret
              name: mongo-secret
              key: MONGO_ROOT_PASSWORD
        image: ghcr.io/auzty/karsajobs:latest # mengambil docker image dari github registry
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 # bind port pod ke 8080
          name: 8080tcp02
          protocol: TCP
