apiVersion: v1
kind: Service
metadata:
  name: karsajobs-service
spec:
  type: NodePort
  selector:
    app: karsajobs
  ports:
  - name: tcp8080
    port: 8080
    targetPort: 8080
    nodePort: 30002