apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui-service
spec:
  type: NodePort
  selector:
    app: karsajobs-ui
  ports:
  - name: tcp8000
    port: 8000
    targetPort: 8000
    nodePort: 30001